export const cities = [
  {
    value: 'Cần Thơ',
    label: 'Cần Thơ',
    province: 'Cần Thơ',
    area: '1,408.9',
    population: '1,248,000',
  },
  {
    value: 'Đà Nẵng',
    label: 'Đà Nẵng',
    province: 'Đà Nẵng',
    area: '1,285.4',
    population: '1,028,000',
  },
  {
    value: 'Hải Phòng',
    label: 'Hải Phòng',
    province: 'Hải Phòng',
    area: '1,527.4',
    population: '1,963,300',
  },
  {
    value: 'Hà Nội',
    label: 'Hà Nội',
    province: 'Hà Nội',
    area: '3,324.5',
    population: '7,216,000',
  },
  {
    value: 'Hồ Chí Minh',
    label: 'Hồ Chí Minh',
    province: 'Hồ Chí Minh',
    area: '2,095.5',
    population: '8,146,300',
  },
  {
    value: 'Bà Rịa',
    label: 'Bà Rịa',
    province: 'Bà Rịa–Vũng Tàu',
    area: '91.46',
    population: '122,424',
  },
  {
    value: 'Bạc Liêu',
    label: 'Bạc Liêu',
    province: 'Bạc Liêu',
    area: '175.4',
    population: '188,863',
  },
  {
    value: 'Bắc Giang',
    label: 'Bắc Giang',
    province: 'Bắc Giang',
    area: '32.21',
    population: '126,810',
  },
  {
    value: 'Bắc Ninh',
    label: 'Bắc Ninh',
    province: 'Bắc Ninh',
    area: '80.28',
    population: '272,634',
  },
  {
    value: 'Bảo Lộc',
    label: 'Bảo Lộc',
    province: 'Lâm Đồng',
    area: '232.56',
    population: '153,362',
  },
  {
    value: 'Biên Hòa',
    label: 'Biên Hòa',
    province: 'Đồng Nai',
    area: '264.07',
    population: '1,104,495',
  },
  {
    value: 'Bến Tre',
    label: 'Bến Tre',
    province: 'Bến Tre',
    area: '67.48',
    population: '143,312',
  },
  {
    value: 'Buôn Ma Thuột',
    label: 'Buôn Ma Thuột',
    province: 'Đắk Lắk',
    area: '370.00',
    population: '340,000',
  },
  {
    value: 'Cà Mau',
    label: 'Cà Mau',
    province: 'Cà Mau',
    area: '250.3',
    population: '204,895',
  },
  {
    value: 'Cẩm Phả',
    label: 'Cẩm Phả',
    province: 'Quảng Ninh',
    area: '486.4',
    population: '195,800',
  },
  {
    value: 'Cao Lãnh',
    label: 'Cao Lãnh',
    province: 'Đồng Tháp',
    area: '107.195',
    population: '149,837',
  },
  {
    value: 'Châu Đốc',
    label: 'Châu Đốc',
    province: 'An Giang',
    area: '105.290',
    population: '157,298',
  },
  {
    value: 'Đà Lạt',
    label: 'Đà Lạt',
    province: 'Lâm Đồng',
    area: '393.29',
    population: '256,393',
  },
  {
    value: 'Điện Biên Phủ',
    label: 'Điện Biên Phủ',
    province: 'Điện Biên',
    area: '60.09',
    population: '70,639',
  },
  {
    value: 'Đông Hà',
    label: 'Đông Hà',
    province: 'Quảng Trị',
    area: '73.06',
    population: '93,756',
  },
  {
    value: 'Đồng Hới',
    label: 'Đồng Hới',
    province: 'Quảng Bình',
    area: '155.54',
    population: '160,325',
  },
  {
    value: 'Hà Tĩnh',
    label: 'Hà Tĩnh',
    province: 'Hà Tĩnh',
    area: '56.19',
    population: '117,546',
  },
  {
    value: 'Hạ Long',
    label: 'Hạ Long',
    province: 'Quảng Ninh',
    area: '208.7',
    population: '203,731',
  },
  {
    value: 'Hải Dương',
    label: 'Hải Dương',
    province: 'Hải Dương',
    area: '71.39',
    population: '187,405',
  },
  {
    value: 'Hòa Bình',
    label: 'Hòa Bình',
    province: 'Hòa Bình',
    area: '148.2',
    population: '93,409',
  },
  {
    value: 'Hội An',
    label: 'Hội An',
    province: 'Quảng Nam',
    area: '61.47',
    population: '121,716',
  },
  {
    value: 'Huế',
    label: 'Huế',
    province: 'Thừa Thiên–Huế',
    area: '83.3',
    population: '333,715',
  },
  {
    value: 'Hưng Yên',
    label: 'Hưng Yên',
    province: 'Hưng Yên',
    area: '46.8',
    population: '121,486',
  },
  {
    value: 'Kon Tum',
    label: 'Kon Tum',
    province: 'Kon Tum',
    area: '432.98',
    population: '137,662',
  },
  {
    value: 'Lạng Sơn',
    label: 'Lạng Sơn',
    province: 'Lạng Sơn',
    area: '79.0',
    population: '148,000',
  },
  {
    value: 'Lào Cai',
    label: 'Lào Cai',
    province: 'Lào Cai',
    area: '221.5',
    population: '94,192',
  },
  {
    value: 'Long Xuyên',
    label: 'Long Xuyên',
    province: 'An Giang',
    area: '106.87',
    population: '280,300',
  },
  {
    value: 'Móng Cái',
    label: 'Móng Cái',
    province: 'Quảng Ninh',
    area: '518.28',
    population: '108,016',
  },
  {
    value: 'Mỹ Tho',
    label: 'Mỹ Tho',
    province: 'Tiền Giang',
    area: '79.8',
    population: '215,000',
  },
  {
    value: 'Nam Định',
    label: 'Nam Định',
    province: 'Nam Định',
    area: '46.4',
    population: '191,900',
  },
  {
    value: 'Ninh Bình',
    label: 'Ninh Bình',
    province: 'Ninh Bình',
    area: '48.3',
    population: '130,517',
  },
  {
    value: 'Nha Trang',
    label: 'Nha Trang',
    province: 'Khánh Hòa',
    area: '251.0',
    population: '392,279',
  },
  {
    value: 'Cam Ranh',
    label: 'Cam Ranh',
    province: 'Khánh Hòa',
    area: '325.0',
    population: '128,358',
  },
  {
    value: 'Phan Rang–Tháp Chàm',
    label: 'Phan Rang–Tháp Chàm',
    province: 'Ninh Thuận',
    area: '79.37',
    population: '102,941',
  },
  {
    value: 'Phan Thiết',
    label: 'Phan Thiết',
    province: 'Bình Thuận',
    area: '206.0',
    population: '255,000',
  },
  {
    value: 'Phủ Lý',
    label: 'Phủ Lý',
    province: 'Hà Nam',
    area: '34.27',
    population: '121,350',
  },
  {
    value: 'Pleiku',
    label: 'Pleiku',
    province: 'Gia Lai',
    area: '260.61',
    population: '186,763',
  },
  {
    value: 'Quảng Ngãi',
    label: 'Quảng Ngãi',
    province: 'Quảng Ngãi',
    area: '37.12',
    population: '134,400',
  },
  {
    value: 'Quy Nhơn',
    label: 'Quy Nhơn',
    province: 'Bình Định',
    area: '284.28',
    population: '311,000',
  },
  {
    value: 'Rạch Giá',
    label: 'Rạch Giá',
    province: 'Kiên Giang',
    area: '97.75',
    population: '228,360',
  },
  {
    value: 'Sa Đéc',
    label: 'Sa Đéc',
    province: 'Đồng Tháp',
    area: '59.81',
    population: '152,237',
  },
  {
    value: 'Sóc Trăng',
    label: 'Sóc Trăng',
    province: 'Sóc Trăng',
    area: '76.15',
    population: '173,922',
  },
  {
    value: 'Sơn La',
    label: 'Sơn La',
    province: 'Sơn La',
    area: '324.93',
    population: '107,282',
  },
  {
    value: 'Tam Kỳ',
    label: 'Tam Kỳ',
    province: 'Quảng Nam',
    area: '92.63',
    population: '120,256',
  },
  {
    value: 'Tân An',
    label: 'Tân An',
    province: 'Long An',
    area: '81.79',
    population: '166,419',
  },
  {
    value: 'Thái Bình',
    label: 'Thái Bình',
    province: 'Thái Bình',
    area: '67.7',
    population: '270,000',
  },
  {
    value: 'Thái Nguyên',
    label: 'Thái Nguyên',
    province: 'Thái Nguyên',
    area: '189.70',
    population: '330,000',
  },
  {
    value: 'Thanh Hóa',
    label: 'Thanh Hóa',
    province: 'Thanh Hóa',
    area: '57.8',
    population: '197,551',
  },
  {
    value: 'Trà Vinh',
    label: 'Trà Vinh',
    province: 'Trà Vinh',
    area: '68.03',
    population: '131,360',
  },
  {
    value: 'Tuy Hòa',
    label: 'Tuy Hòa',
    province: 'Phú Yên',
    area: '212.62',
    population: '167,174',
  },
  {
    value: 'Tuyên Quang',
    label: 'Tuyên Quang',
    province: 'Tuyên Quang',
    area: '119.17',
    population: '110,119',
  },
  {
    value: 'Uông Bí',
    label: 'Uông Bí',
    province: 'Quảng Ninh',
    area: '256.3',
    population: '170,000',
  },
  {
    value: 'Việt Trì',
    label: 'Việt Trì',
    province: 'Phú Thọ',
    area: '110.99',
    population: '277,539',
  },
  {
    value: 'Vinh',
    label: 'Vinh',
    province: 'Nghệ An',
    area: '104.98',
    population: '282,981',
  },
  {
    value: 'Vĩnh Yên',
    label: 'Vĩnh Yên',
    province: 'Vĩnh Phúc',
    area: '50.80',
    population: '122,568',
  },
  {
    value: 'Vĩnh Long',
    label: 'Vĩnh Long',
    province: 'Vĩnh Long',
    area: '48.01',
    population: '147,039',
  },
  {
    value: 'Vũng Tàu',
    label: 'Vũng Tàu',
    province: 'Bà Rịa–Vũng Tàu',
    area: '141.1',
    population: '327,000',
  },
  {
    value: 'Yên Bái',
    label: 'Yên Bái',
    province: 'Yên Bái',
    area: '108.155',
    population: '95,892',
  },
  {
    value: 'Cao Bằng',
    label: 'Cao Bằng',
    province: 'Cao Bằng',
    area: '107.6',
    population: '84,421',
  },
];
